print("Welcome to the Turn-Based Game\n")
print("Choose Chacater:\n1:Warrior:\nSpecializes in high Health and Damage but has lower Defence and Speed\n\nSpecial Move: All IN \nUses 4 Mana does double damage but for the rest of the match damage is cut in half\n\nGaurdian Angel: When the Warrior Health hits zero it is replaced with 1\n")
print("2:Mage\nWell rounded stats with high Mana\n\nSpecial Move: Rock Slam\nUse 2 mana to slam a rock on the enemy stuning them a turn, but dealing only half damage\n\n")
print("3:Rouge\nExtremely high damage and speed with low defence and health\n\nSpecial Move: Speed Blitz\nUse 2 mana to boost your speed to catch an enemy off guard dealing 25% more damage and doubling your evaision the next turn\n\n")
x = int(input())
